/**
 * Consistent, machine-readable error codes used across the API.
 * Field-level validation errors reference these codes; operational errors use them too.
 */
export const ErrorCodes = {
  // ==================== Generic ====================
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FIELD_REQUIRED: 'FIELD_REQUIRED',
  INVALID_TYPE: 'INVALID_TYPE',
  INVALID_VALUE: 'INVALID_VALUE',
  TOO_SMALL: 'TOO_SMALL',
  TOO_BIG: 'TOO_BIG',
  INVALID_ENUM: 'INVALID_ENUM',
  INVALID_FORMAT: 'INVALID_FORMAT',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',

  // ==================== Auth ====================
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',

  // ==================== Validation fields ====================
  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  INVALID_EMAIL: 'INVALID_EMAIL',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
  PASSWORD_REQUIREMENTS: 'PASSWORD_REQUIREMENTS',
  NAME_REQUIRED: 'NAME_REQUIRED',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_COUNTRY: 'INVALID_COUNTRY',
  INVALID_DATE_OF_BIRTH: 'INVALID_DATE_OF_BIRTH',
  INVALID_ID_TYPE: 'INVALID_ID_TYPE',
  ID_NUMBER_REQUIRED: 'ID_NUMBER_REQUIRED',
  INVALID_ID_NUMBER: 'INVALID_ID_NUMBER',
  INVALID_INTEREST: 'INVALID_INTEREST',
  INVALID_SKILL: 'INVALID_SKILL',
  INVALID_AVAILABILITY_DAY: 'INVALID_AVAILABILITY_DAY',
  INVALID_AVAILABILITY_TIME: 'INVALID_AVAILABILITY_TIME',
  INVALID_ORGANIZATION_TYPE: 'INVALID_ORGANIZATION_TYPE',
  INVALID_MASJID_SERVICE: 'INVALID_MASJID_SERVICE',
  INVALID_TRUSTEE_ROLE: 'INVALID_TRUSTEE_ROLE',
  INVALID_WEBSITE: 'INVALID_WEBSITE',
  INVALID_ESTABLISHED_YEAR: 'INVALID_ESTABLISHED_YEAR',
  AT_LEAST_ONE_TRUSTEE_REQUIRED: 'AT_LEAST_ONE_TRUSTEE_REQUIRED',
  AT_LEAST_ONE_DOCUMENT_REQUIRED: 'AT_LEAST_ONE_DOCUMENT_REQUIRED',
  INVALID_DENIAL_REASON: 'INVALID_DENIAL_REASON',

  // ==================== OTP ====================
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_LOCKED: 'OTP_LOCKED',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  OTP_MAX_RESENDS: 'OTP_MAX_RESENDS',
  OTP_ALREADY_VERIFIED: 'OTP_ALREADY_VERIFIED',
  INVALID_OTP: 'INVALID_OTP',
  EXPIRED_OTP: 'EXPIRED_OTP',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',
  PENDING_REGISTRATION_EXISTS: 'PENDING_REGISTRATION_EXISTS',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  SERVER_ERROR: 'SERVER_ERROR',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',

  // ==================== Registration workflow ====================
  REGISTRATION_STEP_INVALID: 'REGISTRATION_STEP_INVALID',
  REGISTRATION_NOT_FOUND: 'REGISTRATION_NOT_FOUND',
  REGISTRATION_COMPLETE: 'REGISTRATION_COMPLETE',
  REGISTRATION_NOT_DENIED: 'REGISTRATION_NOT_DENIED',
  REGISTRATION_NOT_PENDING: 'REGISTRATION_NOT_PENDING',
  EMAIL_VERIFICATION_REQUIRED: 'EMAIL_VERIFICATION_REQUIRED',
  MASJID_ALREADY_SUBMITTED: 'MASJID_ALREADY_SUBMITTED',

  // ==================== File upload ====================
  FILE_REQUIRED: 'FILE_REQUIRED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  INVALID_FILE_SIGNATURE: 'INVALID_FILE_SIGNATURE',
  CLOUDINARY_NOT_CONFIGURED: 'CLOUDINARY_NOT_CONFIGURED',
  CAMPAIGN_NOT_FOUND: 'CAMPAIGN_NOT_FOUND',
  CAMPAIGN_INCOMPLETE: 'CAMPAIGN_INCOMPLETE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
